### ISSUE TITLE
SMTP password saving fails

### ISSUE THREAD

**Issue by tiloschroeder** [symphonycms/symphony-2#2763] opened 2017-10-01 20:28 UTC
Affected Symphony version(s) :2.6.11, 2.7.0

I've tried to use a password with a "less then" character, e.g. '123<456', in the Symphony Preferences for a SMTP Gateway.  Only '123' will be stored.

**Comment by michael-e** [comment] 2017-10-01 20:47
Confirmed. This is a bug. (I really wonder why nobody ever experienced it before.)

**Comment by jurajkapsz** [comment] 2017-10-01 21:24
> (I really wonder why nobody ever experienced it before.)

Interesting, that I never had a `<` symbol in my passwords, not even in generated ones and all my passwords that I use or have ever used are unique.

**Comment by nitriques** [comment] 2017-10-20 17:19
Yeah wow super find, never had this problem also !

I this is strip_tags that does this. It is really hard to sanitize passwords.

**Comment by michael-e** [comment] 2017-10-23 20:02
Why does Symphony use `strip_tags` for the Email Gateway preferences?

I tried the same (`<` in a password) for senders in the Email Newsletter Manager (which also uses the email gateways). The "sender" page will break, but just because the email gateways don't sanitize the values when building the input widgets.

So my first suggestion is to sanitize the values when buikding the `Widget::Input` stuff. This would at least fix issues with the Email Newsletter Manager. Then one could try and fix Symphony's preferences.

@nitriques: I can send a PR for the sanitizing, if you like. Should I?

**Comment by nitriques** [comment] 2017-10-23 23:52
> @nitriques: I can send a PR for the sanitizing, if you like. Should I?

Yes please.

We should not touch the password when saving it (only `'` escaping is needed).

BTW, returning passwords to the user is kind of a non sense to me.

**Comment by michael-e** [comment] 2017-10-25 15:43
My pull request #2769 prevents invalid HTML if any value contains a `<` character, for example. All values are sanitized (which is good practice, IMHO). However, it does not fully solve the issue in this thread. The problem that is left is **saving** the values.

**Comment by nitriques** [comment] 2018-01-17 23:06
Fixed in #2781 which got merged into `2.7.x` branch

**Closed** 2018-02-01 16:13 UTC
Labels: 1 - Minor, Fix found, Fixed in 2.7.x, PR Submitted
