### ISSUE TITLE
Backend publish index table unambiguous sorting

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/symphony-2#2856] opened 2018-07-23 21:50 UTC
Affected Symphony version(s) : 2.7.7 (all?)
PHP version(s) : 7.2
OS(es) : All

Don't know how much it is related to #2498 - guess the same issue but this time concerning backend publish index - but:

**Use case**
Having paginated section entries in a publish backend index, sorted by a field (column) which has the same value across all or most of the entries, e.g. a `yes` value checkbox field.

**Issue**
Not all entries are shown when paginating the index table; entries are randomized or being repeated on subsequent pages.

**Expected**
To be able to browse through all entries in section.

**Comment by munki-boy** [comment] 2018-07-23 22:12
I can't replicate this issue.

What about some extension overriding the sort order?

**Comment by jurajkapsz** [comment] 2018-07-23 23:05
> I can't replicate this issue.

Also @jonmifsud confirmed this on [gitter chat](https://gitter.im/symphonycms/symphony-2?at=5b55ed75ee530e4aac90dd0a) that he came accross this a few times.

My original posting is [right above](https://gitter.im/symphonycms/symphony-2?at=5b55ecb3ee530e4aac90db10) that comment.

Actually I came across this for the first time in years. I can't share a sample of the data, because it's private data; basically it's a list of users with some yes / no attributes.

**Comment by munki-boy** [comment] 2018-07-23 23:32
I understand. I just had another look and I'm using Entry Relationship Field on that site.

I'm sure @jonmifsud 's answer will be correct.  :100:

**Comment by jurajkapsz** [comment] 2018-07-24 08:54
Guys, I can further specify, that:

- When I filter the index through an association (list associated entries), this issue does not occur, everything is fine;
- When I don't filter the index - just listing through the whole section; entries having the same 
"yes" value (or "no" in my case, but that does not matter I would say) and sorting by such a column - it does occur.

**Comment by nitriques** [comment] 2018-09-26 02:55
So the issue is not related to filtering, but only to sorting ???

**Comment by nitriques** [comment] 2018-09-26 03:03
I confirm some weird behaviour.. I'll investigate on Thursday.

**Comment by jurajkapsz** [comment] 2018-09-26 07:29
> So the issue is not related to filtering, but only to sorting ???

I believe so. If I sort unfiltered section, it does happen; if a filtered section, it does not.

**Comment by jonmifsud** [comment] 2018-09-28 04:03
I would guess yes anything with a non-deterministic sort has the problem.
My suggestion would be to add a secondary sort by entry id for the sort.

**Comment by michael-e** [comment] 2018-09-28 05:51
@nitriques Now as you mention it… Yes, I also have a "date field hack" in my big system, and the private commit is called "Prevent random sort results for identical dates". Guess what? I added sorting by system ID. :-)

**Comment by nitriques** [comment] 2018-09-30 18:32
@jonmifsud @michael-e Thanks guys!

**Comment by jurajkapsz** [comment] 2018-09-30 18:45
@nitriques Is the `Fixed in 3.0.x` label correct? I am thinking if it shouldn't be `2.7.x`...

**Comment by nitriques** [comment] 2018-10-01 19:50
@jurajkapsz Yes it is fixed in 3.0.x (since the fix is different) but it should also be fixed in 2.7.x when #2872 will be merged.

**Closed** 2019-03-19 18:10 UTC
Labels: 2 - Nominal, Fix found, Fixed in 2.7.x, Fixed in 3.0.x, PR Submitted
