### ISSUE TITLE
Session fails to set on subdomains.

### ISSUE THREAD

**Issue by brendo** [symphonycms/symphony-2#2842] opened 2018-05-20 17:26 UTC
Affected Symphony version(s) : 2.7.6
PHP version(s) : 5.5.19 (haven't tested 7 yet)

Encountered a scenario today that was a little tricky to repeat:

- Main domain, `https://www.example.org`
- Dev domain, `http://dev.example.org`

1. Login to Symphony on the main domain ✔️ 
2. Login to Symphony on the dev domain 🙅‍♂️ 
3. Logout of Symphony on the main domain
4. Login to Symphony on the dev domain ✔️ 
5. Login to Symphony on the main domain 🙅‍♂️ 

The reason behind this weirdness appears to be the [`session.name`](http://us1.php.net/manual/en/function.session-name.php) setting. We don't set it in Symphony at all, so by default it is `PHPSESSID`.

When we attempt to login on the dev domain, it won't replace the cookie that was set previously (not too sure why?), so the login fails. You can see in the database that the session is actually created correctly, but the cookie just won't be set.

To fix it I set the `session.name` (just hardcoded it to a different string).

For a long term fix, perhaps we should set this value using the `getDomain()` method? The return value would need to be cleaned up to be [alphanumeric](http://us1.php.net/manual/en/session.configuration.php#ini.session.name) but it should solve the issue...

**Comment by brendo** [comment] 2018-05-20 17:27
Oh and yes, I tested with the #2820 patch as well.

**Comment by nitriques** [comment] 2018-05-22 21:34
Thanks @brendo ! This is great! But I feel like it is a breaking change, and would get merged into `3.0.0`.

Could we fix this in LTS by setting the domain name without a preceding dot ?

**Comment by michael-e** [comment] 2018-05-22 21:43
I am not sure if this is needed, and it may have a lot of side effects. Have I understtod correctyl? Does this change the cookie's name from `PHPSESSID` to something derived from the domain? This would definitely break my setups, at least.

@brendo, are you sure that your problems were not simply caused by the fact that one of the domains was running with SSL, the other did not? (In this case you will have a "secure" cookie on the first domain, which may cause your issues.)

If you think that this is useful, please give me some days to test it and dive into it.

**Comment by nitriques** [comment] 2018-05-23 01:56
> Does this change the cookie's name from PHPSESSID to something derived from the domain?

That's what I've also understood. That's why my fix is to be more strict on the domain value, never setting the cookie to be valid on the root when it hits www.
You log on one host, that should only be valid for a that single host.

That being said, I have nothing *against* letting user set the cookie name.

**Comment by brendo** [comment] 2018-05-23 20:12
> @brendo, are you sure that your problems were not simply caused by the fact that one of the domains was running with SSL, the other did not? (In this case you will have a "secure" cookie on the first domain, which may cause your issues.)

That could definitely be the case. Will retest once I get SSL on the subdomain!

**Comment by nitriques** [comment] 2018-06-01 21:16
:+1:

**Comment by michael-e** [comment] 2018-06-02 16:29
Let's wait for @brendo's SSL test.

**Closed** 2018-06-08 19:43 UTC
Labels: 2 - Nominal
