### ISSUE TITLE
Make DS params in XML optional

### ISSUE THREAD

**Issue by lewiswharf** [symphonycms/symphony-2#784] opened 2011-09-23 01:10 UTC
I would like to see a setting to turn on and off the parameter output to XML in `class.frontendpage.php` starting on line 444.  

**Use case**: when outputting a `$ds-datasource-parameter` such as IDs to be used as a filter in another data source, there can be unnecessary overhead when the number of IDs is significant. 

What do you guys think?

**Comment by michael-e** [comment] 2016-02-16 14:29
This is an old thread, but I also experienced a massive performance issue just because one data source was outputting around 1000 IDs (which were added to the parameter XML node). I hacked a solution, but I would like to share some thoughts on this. Please close this issue again if you feel that I am on the wrong track.

The decision to add parameters to page XML was absolutely right (and we should completely drop passing "parameters as arguments" to the XSL processor in a future release). But at that time, we did not see that DS parameters play a special role. Their main task is to allow DS filtering/chaining. Keeping them in the param pool is not strictly necessary (because you can always add field output to XML if you need these values for templating).

Given the performance issues that may arise I suggest to **add a configuration option to Symphony** which allows to omit data source parameters from page XML (which was the original intention of this thread).

We might, of course, open new issues to discuss more elaborate solutions. Maybe we should have a new  page in the debugger extension to show these parameters (no matter if they are kept in the param pool or not). Maybe we should remove DS params completely (from what we currently think is "normal params")? Maybe we think about deciding this on a per-data-source basis (which would probbly get rather complicated)? I don't know, but I think that this should be discussed separately.

BTW, currently my solution is to use the `FrontendParamsResolve` delegate with a callback like this:

```php
public function frontendParamsPostResolve($context)
{
    if (Symphony::Configuration()->get('add_ds_params_to_xml', 'custom_config') === 'no') {
        foreach ($context['params'] as $key => $value) {
            if (substr($key, 0, 3) === 'ds-') {
                unset($context['params'][$key]);
            }
        }
    }
}
```

If somebody has a better idea, I am all ears!

**Comment by nitriques** [comment] 2016-02-16 16:23
I do not think that the setting should be on a site basis, but more on the data source level...

Ever went on that path Micheal ?

**Comment by jonmifsud** [comment] 2016-02-16 16:26
Datasource level seems to make most sense to me. I do have datasources
where I don't need this and others where having it would be nice.

**Comment by michael-e** [comment] 2016-02-16 16:43
Let's assume that a developer must make a decision for every data source. He asks: "Why should I omit/remove these parameters?" You will answer: "It makes your site faster, and you don't really need those parameters, they are intended for internal use." What would the developer say then? "Why do I have to decide this for every data source then?" or maybe: "Why do I have to decide this at all?" He probably wouldn't say "It's cool to have an option in every DS to slow down the site."

The proper long term solution, in my eyes, is to remove these parameters completely from the param pool and use them for DS chaining exclusively. Separate "params" from "DS params". Of course the debugger would need a **new page then to show those DS params**.

The simplest short term solution is to add a global config option. Honestly, in my "big system" I have not found more than 6 occurences in the templating layer making use of DS parameters. And it was pretty simple to remove them.

**Comment by nitriques** [comment] 2016-02-16 17:01
Your arguments are indeed right, but I fear that a single on/off switch might not be flexible enough.

> Separate "params" from "DS params". Of course the debugger would need a new page then to show those DS params.

The more I think about it, the more I see to separate concerns: XML output params (which I use quite often) and "filtering values" for chaining and filtering.

But now the question is: how to change this ? Are current output parameters only for filtering (and we add the xml param) or the other way around ?

**Comment by michael-e** [comment] 2016-02-16 17:28
> a single on/off switch might not be flexible enough

DS params don't provide any additional functionality for XSLT templating. Everything can be done with DS output. So we wouldn't compromise flexibility at all.

> The more I think about it, the more I see to separate concerns: XML output params (which I use quite often) and "filtering values" for chaining and filtering.

Exactly! And that is why we should aim to completely remove the "filtering values" from XML on the long run.

> Are current output parameters only for filtering (and we add the xml param) or the other way around ?

I see output parameters as useful for templating. Think of the "standard" parameters like the sitename, for example. The filtering values on the other hand could live in a new array, internally, and exposed by a special debugging page. But that is the long term solution (and it's potentially breaking sites). Short term, pretty close to this (but non-breaking), is my suggestion to have a global config option to unset the DS params immediately before the are:

* added to XML
* added as arguments to the processor call (deprecated, but still alive)

The downside of my described "hack" is the fact that I can never be sure that a leading `ds-` identifies a datasource parameter. It might as well be some custom parameter (e.g. the "DS Double Super Param", `ds-double-super-param`) provided by an extension. If we tend to say that `ds-` is a *reserved string* (for Symphony DS params), I don't see any issues. :-)

**Comment by nitriques** [comment] 2016-02-16 17:42
> remove the "filtering values" from XML on the long run.

Agreed.

> The filtering values on the other hand could live in a new array, internally, 

Agreed.

> and exposed by a special debugging page

I do not agree. It should be output if the DS wants it so. There should also be a dedicated xml node for them (instead of `ds-` prefix)

**Comment by michael-e** [comment] 2016-02-16 17:48
> It should be output if the DS wants it so.

Why? As I said, it can't do anything for templating that can not be done with standard DS output. Or am I missing something?

**Comment by jonmifsud** [comment] 2016-02-16 18:54
Hmm can't think of a usecase which uses the ds param in xslt that can't be
done with standard output.

**Comment by nitriques** [comment] 2016-02-16 19:32
> As I said, it can't do anything for templating that can not be done with standard DS output. Or am I missing something?

I was thinking about a list of ids. But yeah, I could create an empty DS returning only entry ids so I guess you are right!

**Comment by michael-e** [comment] 2016-02-16 20:24
No, you are indeed right. At the moment Symphony outputs an empty DS node (without entry nodes, which means without IDs) if nothing is seleted for output. If you need entry nodes, you have to select a field, or at least the system:pagination element:

```xml
<test cache-age="fresh">
	<pagination total-entries="22254" total-pages="1113" entries-per-page="20" current-page="1"/>
	<section id="6" handle="meldungen">News</section>
	<entry id="307462"/>
	<entry id="307460"/>
	<entry id="307457"/>
	...
</test>
```

**Comment by michael-e** [comment] 2016-02-16 20:25
(Which is fine for me.)

**Comment by nitriques** [comment] 2016-02-16 21:19
> you have to select a field,

Would system:id work ?

**Comment by michael-e** [comment] 2016-02-16 21:26
Wait, let me test...

**Comment by michael-e** [comment] 2016-02-16 21:28
Oh no, it's not selectable at all in "included elements". There's `system: pagination` and `system: date`…

It feels like something's missing. :-(

**Comment by brendo** [comment] 2016-02-16 23:40
I actually have one scenario where I use the `/data/params` information, and I'm not too sure how else I can achieve the same result... maybe someone here will know!

When using the Association Field with multiple options, the author is allowed to drag and drop the entries around to form a sort order. As I don't want to incur the performance overhead of including this data inside the datasource, I output the parameters and create another datasource that filters off those parameters.

Unfortunately the custom sort order is lost on that chained datasource, so the only way I can output the data in the same sort order as the author defined is to loop over the parameters and then call the entry individually:

```xsl
<xsl:template match='my-ds'>
    <xsl:variable name='ds' select='.' />

    <xsl:for-each select='/data/params/my-ds.association-field/item'>
        <xsl:apply-templates select='$ds/entry[@id = current()]' />
    </xsl:for-each>
</xsl:template>
```

I originally thought the fix could be applied to the chained DS, but that breaks the concept of DS which have filters from multiple DS.

Ideas?

---

I'm also curious why & where the performance bottleneck occurred. Outputting 1000 nodes shouldn't bring the system to a halt :(

**Comment by munki-boy** [comment] 2016-02-16 23:54
@brendo Nils once told me there'd be a lot of overhead if you drill down without using a separate DS but I didn't know why. I switched to entry_relationship_field instead because it doesn't seem to have that problem.

**Comment by michael-e** [comment] 2016-02-17 00:01
Hi @brendo, I see your point. It would be great to know how big the performance overhead would be if your data currently outputted as (data source) parameters is also included in the standard XML output. I have no idea. Could you maybe test this?

I do have numbers for my situation: I am talking about my "big system" (you may remember that); in the past months I have tuned it with Zend Opcache and a data source caching layer. Now when all data sources are read from the cache, building the page in question took 0.30 seconds total (which was indeed slow compared to other pages, hence my profiling/debugging). After removing remove those 1000 parameters from the param pool, the page takes 0.15 seconds, which is half the time! I have tested this several times—on my machine it obviously takes 150ms to build 1000 param values.

**Comment by michael-e** [comment] 2016-02-17 00:21
I did a short test with my setup. I had to include the entry titles in the output in order to get the entry IDs, and this took an extra 0.20 seconds in my case. (Unfortunately, it is not possible to output the IDs only, see above.)

If we fix this (allow to output `system:id` only in data sources), I would assume that the standard output XML wouldn't take any longer than the DS param XML. So you wouldn't lose anything in your scenario. But every site would gain to a certain extend.

**Comment by michael-e** [comment] 2016-02-17 00:26
If somebody can tell my how to hack the section data source to include `system:id` only in the output, I can try and verify my above assumption. It would be interesting, because DS output would be `<entry id="123"/>` instead of `<item>123</item>` — shouldn't the first one take longer (which would prove me wrong)?

**Comment by nitriques** [comment] 2016-02-17 15:29
@brendo is right: The sort order is lost. I knew I also had something that would need this kind of behavior.

@michael-e can you try to edit the php file of the DS to set it to system:id ?

**Comment by nitriques** [comment] 2016-02-17 15:32
@munki-boy 

> I switched to entry_relationship_field instead because it doesn't seem to have that problem.

it has other problems tho ;)

**Comment by michael-e** [comment] 2016-02-17 16:44
This gets better every day.

* including 1000 entry IDs in the XML params node takes 150ms (as posted above)
* including 1000 entry IDs (<entry id="123"/>) in standard XML output takes no time. At least not notable.

How can that be?

**Comment by nitriques** [comment] 2016-02-17 17:03
Wow I seriously do not know...

**Comment by michael-e** [comment] 2016-02-17 17:03
The biggest performance hickup in the params in building handles using:

````php
$item->setAttribute('handle', Lang::createHandle($value));
```

I have sent a pull request to integration concerning this which has been pulled: https://github.com/symphonycms/symphony-2/pull/2377. But it has not been changed in 2.6.x because it is might be a breaking change if people *would* use the parameter handle in XSLT templates.

Now I have:

* including 1000 entry IDs in the XML params node (as `<item handle="123">123</item>`) takes 150ms (as posted above)
* including 1000 entry IDs in the XML params node **without handles** (as `<item>123</item>`) takes 150ms (as posted above)
* including 1000 entry IDs in standard XML output (as `<entry id="123"/>`) takes no time. At least not notable. Maybe 2ms…

**Comment by nitriques** [comment] 2016-02-17 17:04
Wow ! I did not knew that creating handles was such long!

**Comment by michael-e** [comment] 2016-02-17 17:05
It might be the language stuff?

**Comment by nitriques** [comment] 2016-02-17 17:05
Regexp... ?

**Comment by michael-e** [comment] 2016-02-17 17:05
That would explain it.

Now I will try and find the remaining 25ms.

**Comment by nitriques** [comment] 2016-02-17 17:12
;) Thanks Michael!

**Comment by michael-e** [comment] 2016-02-17 17:36
I am already down to <10ms difference. :-)) The remaining difference might be caused by a testing hack. I will be back at the keyboard a bit later (2 hours or so).

**Comment by nitriques** [comment] 2016-02-17 18:01
:+1:

**Comment by munki-boy** [comment] 2016-02-17 19:49
@nitriques They both have problems, you have to pick the one with the least for the project you're working on :)

**Comment by nitriques** [comment] 2016-02-17 20:17
@munki-boy Exactly!

**Comment by michael-e** [comment] 2016-02-17 20:28
Still Symphony's speed shouldn't be compromised without need. That's why I make all those tests.

**Comment by nitriques** [comment] 2016-02-17 20:33
> That's why I make all those tests.

And I am gracefull you do ;)

**Comment by michael-e** [comment] 2016-02-17 22:43
It's hard to test page generation differences below 20ms reliably, but I would say:

* it's fastest to not output anything from a datasource (haha)
* it's no big deal (plus 2ms or so) to output 1000 IDs to standard XML (as `<entry id="123"/>`) — currently Symphony is missing the possibility to output IDs only, so this should definitely be added
* it's a bit slower (around 15ms, I couldn't find out *why* this is slower) to ouput 1000 IDs to the param pool (as `<item>123</item>`) if you omit the "legacy style" param output (`ds-datasource-handle`); removing that legacy style is on the list, AFAIK — unfortunately it's a breaking change
* it's again a bit slower (plus 15ms) to additionally output legacy style parameters — Symphony does this at the moment; at this point we are nearly 30ms behind ouputting those IDs to standard XML only, but it will get much worse!
* it's terribly slow (plus 150ms, approx.) to ouput handles for those 1000 IDs to the params XML as well, like **Symphony does it** it at the moment — unfortunately removing the handles is a breaking change as well

All this has been tested on my production server, which is very fast. So with vServers or even shared hosting, you should await bigger numbers.

I will try and post suggestions how to fix this (short-term and long-term) tomorrow. I don't want to spoil a party, so I better think twice. :-)

**Comment by nitriques** [comment] 2016-02-18 00:45
Thanks a lot Michael.

**Comment by michael-e** [comment] 2016-02-18 21:33
I was looking for a logical explanation, and I found it.

The difference between adding nodes to standard XML output and adding nodes to the param pool is caused by the way DS caching works. (Of course I used DS caching in my tests to get rid of database performance jitter, I think I mentioned that. It would be very hard or even impossible to benchmark these differences if you rely on thousands of database queries.)

Here it is: If you use DS caching, the output XML will be cached **as a whole**. But cached params will just be added to the param array again, which means that their XML elements will have **to be built from scratch** even for a cached data source. This in turn means that:

* **it doesn't matter** if you build 1000 elements for the params node or for the standard XML output, but
* DS caching will circumvent building new XML objects for XML output only, so if you use DS caching **it actually does matter**—if you use caching, you better use standard output, not params! :-)

Here are the simplified numbers:

* it's fastest to not output anything from a datasource (haha)
* if you use DS caching, it's no big deal (maybe plus 2ms or so) to output 1000 IDs to standard XML (as `<entry id="123"/>`) — currently Symphony is missing the possibility to output IDs only, so this should definitely be added
* if you do not use caching, the same will probably take around 15ms (untested, but "high probability")
* no matter if you use DS caching or not, it takes around 15ms to ouput 1000 IDs to the param pool (as `<item>123</item>`) if you omit the "legacy style" param output (`ds-datasource-handle`); removing that legacy style is on the list, AFAIK — unfortunately it's a breaking change
* no matter if you use DS caching or not, it adds another 15ms to additionally output legacy style parameters — Symphony does this at the moment; at this point we are nearly 30ms behind ouputting those IDs to standard XML only, but it will get much worse!
* no matter if you use DS caching or not, it's terribly slow (plus 150ms, approx.) to ouput handles for those 1000 IDs to the params XML as well, like **Symphony does it** it at the moment — unfortunately removing the handles is a breaking change as well

Still I am thinking about the right way to deal with this. Two of those "optimizing but breaking" changes are already in the integration branch, and so I wonder if this would be a good time to talk about what we want Symphony 3 to be. Theoretically, if we took these breaking changes from integration and released Sym 3.0.0… There would one big advantage: The number of breaking changes would be small, and people could indeed update their installations (with a bit of work, of course, but we could provide instructions). In this case Symphony 3.0.0 wouldn't have many bugs either—we have a very good codebase in this respect at the moment, IMHO. And finally we would get rid of the "Sym 3 hoax nightmare" by just releasing it with a handful of breaking changes. (We embraced semantic versioning, but still Symphony 3 scares us. Why?)

(There are other changes in the integration branch which are much more frightening to me, especially PDO and the cookie/session rewrite. So I would not suggest to include these in Symphony 3.0.0 without excessive testing. They shouldn't be "breaking", should they? So they might as well be introduced in 3.1.0.)

**Comment by nitriques** [comment] 2016-02-18 21:44
> good time to talk about what we want Symphony 3 to be.

I've rebased the branch this morning BTW :) I hope to get it out this summer...

> We embraced semantic versioning, but still Symphony 3 scares us. Why?

I really do not know why. [Here's a good read](https://medium.com/javascript-scene/software-versions-are-broken-3d2dc0da0783#.f6b6nzo7q)

We should also consider renaming the repo to **symphonycms**

> They shouldn't be "breaking", should they? So they might as well be introduced in 3.1.0.)

Those are breaking changes, so it would be 4! Breaking.Features.Fixes.

But I would very like to include them in 3.0.0. Brendan's new logger too.

**Comment by michael-e** [comment] 2016-02-18 22:02
> But I would very like to include them in 3.0.0. Brendan's new logger too.

I have never really understood the PDO stuff. Will it mean that upgrading will become more difficult if you use a lot of custom queries in your extensions?

> Breaking.Feature.Fix.

Nice explanation!

Still, may I suggest that the last "feature version" of Symphony 2 should get some sort of long term support (e.g. "Sym 2.7 LTS") for those who don't dare to upgrade?

BTW, stopping at 2.7 would be a nice coincidence, because Symphony 1 stopped at version 1.7.01, as far as I remember.

**Comment by nitriques** [comment] 2016-02-18 22:23
> Will it mean that upgrading will become more difficult if you use a lot of custom queries in your extensions?

I do not think it will. Maybe only a problems with backticks...

> Still, may I suggest that the last "feature version" of Symphony 2 should get some sort of long term support

I'd like to call it with a cooler name :) Polls are open!

> BTW, stopping at 2.7 would be a nice coincidence

This will depend on the code itself!

**Comment by munki-boy** [comment] 2016-02-18 23:17
"Symphony Classic"

**Comment by nitriques** [comment] 2016-02-19 15:16
Hum I am more searching for a set of names. Like famous scientists or astral bodies....

**Comment by michael-e** [comment] 2016-02-19 15:25
I think that `Symphony 2.7 LTS` sounds pretty cool.

We might add a nickname, like Debian does it. `Symphony 2.7 LTS "Lulu"`, for example.

:-)

**Comment by nitriques** [comment] 2016-02-19 15:27
> We might add a nickname,

That's what I am looking for. But dropping the version in the name. LTS version can get more feature so we can go to 2.8, 2.9...

**Comment by michael-e** [comment] 2016-02-19 15:33
Ah, you mean s.th. like `Symphony 2 LTS "Albert Einstein"`! :-)

**Comment by michael-e** [comment] 2016-02-19 15:34
But wouldn't it mean less hassle to "feature-freeze" an LTS version?

**Comment by jonmifsud** [comment] 2016-02-19 15:39
Hmm might - I think the problem was mainly that up till 2.4 or something
like that each update was breaking. Though I think at some point we need to
start looking at features of 3.0 and start looking for that move.

**Comment by twiro** [comment] 2016-02-19 15:43
> _We might add a nickname, like Debian does it. Symphony 2.7 LTS "Lulu", for example._

Symphony LTS "Brendan" sounds quite nice to me ;)

> _LTS version can get more feature so we can go to 2.8, 2.9..._

Just a noob-question: Facing the fact that Symphony switched to semantic versioning with 2.5 I would have expected the **last** release of the **2.X-branch** to become the LTS-version - wouldn't it get confusing if features were added to 2.7 (LTS) while other (non-breaking?) changes were only added to 2.8 or 2.9...?

**Comment by munki-boy** [comment] 2016-02-19 15:44
I think he said without the version number though? So 2.8... would be sort if internal name.

**Comment by munki-boy** [comment] 2016-02-19 15:46
Not "Heisenberg" people think Breaking Bad on TV

**Comment by michael-e** [comment] 2016-02-19 15:47
> I would have expected the last release of the 2.X-branch to become the LTS-version

That was my thought as well. No new features anymore. "LTS" meaning "don't be afraid to use this and build cool stuff, we will care for bugs (especially security) for quite a while". (I'd say 3 years or so.)

**Comment by twiro** [comment] 2016-02-19 15:48
> _I think he said without the version number though? So 2.8... would be sort if internal name._

Ah, so 2.8 and 2.9 would be _"inofficial"_ version numbers for updates to Symphony LTS (which would drop the _"offical"_ version numbers) - that would make sense... am I getting this right?

**Comment by munki-boy** [comment] 2016-02-19 15:48
That's what I thought - doesn't make it right :)

**Comment by michael-e** [comment] 2016-02-19 15:49
@twiro: In this case what does LTS stand for? "It might as well break, because we are still fiddling with the codebase."???

**Comment by munki-boy** [comment] 2016-02-19 15:50
Long Term Support - someone will be around to fix it.

**Comment by twiro** [comment] 2016-02-19 16:01
> _In this case what does LTS stand for? "It might as well break, because we are still fiddling with the codebase."???_

I was just trying to understand/interpret what Nicolas wrote:

> _"LTS version can get more feature so we can go to 2.8, 2.9..."_

I have no idea what LTS usually stands for in software development - does it imply "no more features" or simply "non-breaking changes/features might be added but if something breaks it will be fixed asap!"

**Comment by nitriques** [comment] 2016-02-19 17:14
> But wouldn't it mean less hassle to "feature-freeze" an LTS version?

Yeah maybe, but I really want the codename to not refer to a particular version. One could want to port some feature to the LTS version. LTS only means we will fix bugs and continue to release new versions of that particular codebase.

> I have no idea what LTS usually stands for in software development 

It means that version will be maintain for a "long" period of time. I would like to see something in the 2-3 years mark.

> wouldn't it get confusing if features were added to 2.7 (LTS) while other (non-breaking?) changes were only added to 2.8 or 2.9...?

No since it will share the same code name. Versions are for computers, names are for humans.

**Comment by nitriques** [comment] 2016-02-19 17:15
Also, maybe or second LTS version would be 3.2 or even 4.1.

**Comment by michael-e** [comment] 2016-02-19 17:41
> LTS only means we will fix bugs and continue to release new versions of that particular codebase.

Would that work? It feels like a workaround, invalidating semantic versioning. @nitriques, maybe I just don't get your idea? I thought:

* Release 2.7 as final Symphony 2 version, with LTS support (fixes only)
* Release 3.0 as fast as possible, with just a handful of breaking changes but high code quality from the start (so people *can* move their projects forward).   
    (Personally I'd rather push some of the breaking changes to Symphony 4 than again risk to have a wonky major release; the PDO implementation seems incomplete and buggy currently, session/cookie stuff requires solid testing)
* Look forward to Symphony 4

> second LTS version would be 3.2 or even 4.1

Yes, that would probably be the case then, depending on how difficult it is to upgrade between versions. If it is difficult, an LTS version makes sense.

**Comment by munki-boy** [comment] 2016-02-19 17:57
An LTS version provides a stable option for use in less heavy environments while freeing people to innovate more with the big version. Without forcing everyone to have the fast private server with ability to install the latest PHP/SQL etc. 

Doing these things with semantic versioning all in one "family" of Symphony might mean selecting an older version of Symphony due to server/hosting requirements and possibly selecting a version with flawed security or other problems. 

LTS version can fill that gap and people who select it won't be requesting bleeding edge features or need support with the problems of bleeding edge features. Less features but stable and reliable. 

I am guessing.

**Comment by nitriques** [comment] 2016-02-19 19:04
> If it is difficult, an LTS version makes sense.

Yup totally.

> Release 2.7 as final Symphony 2 version, with LTS support (fixes only)

That would be the plan, but I do not want to lock that down. LTS release could go to 2.8 if needed.

> An LTS version provides a stable option for use in less heavy environments while freeing people to innovate more with the big version. Without forcing everyone to have the fast private server with ability to install the latest PHP/SQL etc.

Also true! But again, it does not lock anything.

> invalidating semantic versioning

It's not! It's even letting us manage versions without regards on what are considered to be LTS versions (which have codenames).

> Less features but stable and reliable.

Exactly. But we still allow people to backport new features in LTS releases.

**Comment by munki-boy** [comment] 2016-02-19 19:44
No, it doesn't lock anything.  It's like Symphony Lite but we must not say that for it implies the other to be heavy, which it isn't. :)

**Comment by nitriques** [comment] 2018-02-01 23:10
Dupe, tracking #2338 instead

**Comment by michael-e** [comment] 2018-02-02 11:20
I editied the title of this thread in order to better avoid this misunderstanding. This thread is about data source parameters, which are typically used for data source filtering, so including them in XML output is considered unnecessary overhead. #2338 is about generally removing "parameters as arguments" (for the XSLT processor), while keeping them in the XML.

**Comment by nitriques** [comment] 2018-02-15 22:24
Thanks @michael-e

**Closed** 2020-03-27 17:07 UTC
Labels: 3 - Major, Controversial, Fixed in 3.0.x, PR Submitted
