### ISSUE TITLE
When page param == 0, it gets ignored

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/symphony-2#2355] opened 2015-02-20 10:43 UTC
page param 0 gets ignored

**Comment by nitriques** [comment] 2015-02-20 15:29
Could you be a little more specific ?

The name of your param is 0 ?

**Comment by wdebusschere** [comment] 2015-02-20 15:38
Nitriques, value in the url for the param is 0.
Example www.mysite.com/products/0/45
I need to pass 2 parameters, sometimes the first one is empty..

**Comment by nitriques** [comment] 2015-02-20 15:42
What do you get it you add `var_dump($this->param)die; at this line https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/toolkit/class.frontendpage.php#L422 ?

**Comment by wdebusschere** [comment] 2015-02-20 15:51
I get  NULL and Cannot modify header information - headers already sent by if i dont add "die",
with die i get blank screen

**Comment by nitriques** [comment] 2015-02-20 16:02
Wow. Which Symphony are you running ?

**Comment by nitriques** [comment] 2015-02-20 16:03
And if you add the same `var_dump($this->param);die;` here instead https://github.com/symphonycms/symphony-2/blob/integration/symphony/lib/toolkit/class.frontendpage.php#L487

**Comment by wdebusschere** [comment] 2015-02-20 16:08
NULL.. version 2.5.3 updated last night, but seems that i had this problem already in a previous project with an older symphony version also..

**Comment by michael-e** [comment] 2015-02-20 16:08
Using the current integration branch, I get a 404 page if the first of my params is `0`!

**Comment by wdebusschere** [comment] 2015-02-20 16:08
Maybe your datasource is configured to redirect to 404 when no results with filtering param

**Comment by michael-e** [comment] 2015-02-20 16:12
No, I am pretty sure that I removed all datasources.

* example.com/page/1/1/ -- works
* example.com/page/1/0/ -- works
* example.com/page/hello/1/ -- works
* example.com/page/0/1/ -- FAILS (404 page)

**Comment by nitriques** [comment] 2015-02-20 16:12
Wow x2 then!

> example.com/page/1/0/ -- works

Do you have the page page in the xml ?

**Comment by michael-e** [comment] 2015-02-20 16:13
Indeed the page is called "test", and I have:

    <current-page>test</current-page>

**Comment by michael-e** [comment] 2015-02-20 16:14
* example.com/page/99999999999999/1/ -- works

So it can not be caused by any datasource.

**Comment by nitriques** [comment] 2015-02-20 16:41
@wdebusschere stupid me. The var_dump we are looking for is ` var_dump($this->_param)die;` (notice the added _)

Sorry, :(.  Can you re-try ?? :(

**Comment by wdebusschere** [comment] 2015-02-20 16:53
Output:
"page" ["param1"]=> string(3) "444" ["param2"]=> NULL

**Comment by nitriques** [comment] 2015-02-20 16:57
And param2 is the one == 0 I guess ?

**Comment by wdebusschere** [comment] 2015-02-20 16:59
NO, param1 should be 0, param2 444
 my url www.mysite.com/page/0/444/

**Comment by nitriques** [comment] 2015-02-20 17:05
Can you try to replace the [empty call here](https://github.com/symphonycms/symphony-2/blob/2.5.3/symphony/lib/toolkit/class.frontendpage.php#L647) by `strlen($page_extra_bits) > 0` ?

**Comment by nitriques** [comment] 2015-02-20 17:06
Because `empty('0') === true`

See: http://php.net/manual/en/function.empty.php

> Return Values
>
> Returns FALSE if var exists and has a non-empty, non-zero value. Otherwise returns TRUE.
>
> The following things are considered to be empty:
> 
> "" (an empty string)
> 0 (0 as an integer)
> 0.0 (0 as a float)
> "0" (0 as a string)
> NULL
> FALSE
> array() (an empty array)
> $var; (a variable declared, but without a value)

**Comment by michael-e** [comment] 2015-02-20 18:06
Nope, that doesn't work if you have multiple params:

> Symphony Warning: strlen() expects parameter 1 to be string, array given

**Comment by nitriques** [comment] 2015-02-20 18:12
Damn.

**Comment by michael-e** [comment] 2015-02-20 18:12
I have the feeling that things go wrong much earlier. Investigating…

**Comment by nitriques** [comment] 2015-02-20 18:13
Thanks Michael, I really feel like this is bug... And pretty sure it has to do with a empty call.

**Comment by michael-e** [comment] 2015-02-20 18:26
OK, the first thing that I found out is: Resolving the path/handle/params/extra_bits (and the like) is pretty adventurous. :-)

If you add:

```php
var_dump($page_extra_bits); die();
```

to [this line](https://github.com/symphonycms/symphony-2/blob/2.5.3/symphony/lib/toolkit/class.frontendpage.php#L612), then call a page like `/test/1/1/`, you get:

	array(2) {
	  [0]=>
	  string(1) "1"
	  [1]=>
	  string(1) "1"
	}

If your URL is like `/test/1/0/`:

	array(2) {
	  [0]=>
	  string(1) "0"
	  [1]=>
	  string(1) "1"
	}

BUT if it is `/test/0/1/`, you see:

	array(1) {
	  [0]=>
	  string(1) "1"
	}

Must have to do with `array_pop`ping. :-))

**Comment by nitriques** [comment] 2015-02-20 18:29
> Must have to do with array_popping. :-))

Looks like it! or maybe `array_filter` or `array_map`

**Comment by michael-e** [comment] 2015-02-20 18:32
The preceding lines show that the array gets popped: https://github.com/symphonycms/symphony-2/blob/2.5.3/symphony/lib/toolkit/class.frontendpage.php#L599-L611

**Comment by michael-e** [comment] 2015-02-20 18:35
But as I said, it looks a bit adventurous. Fixing this is a job for a brave man.

**Comment by michael-e** [comment] 2015-02-20 18:38
I am pretty sure that both phenomenons (omitting the param or throwing a 404) are caused by the above misbehaviour. Probably it's just the 404 logic that has been changed a bit. (I remember us working on that from time to time.)

**Comment by nitriques** [comment] 2015-02-20 18:40
Do you have a proposed fix ? :smile:

**Comment by michael-e** [comment] 2015-02-20 18:49
Nope, as I said, brave men only… What about you?

**Comment by michael-e** [comment] 2015-02-20 18:50
Honestly, I don't see the big picture in this code, but maybe @brendo can help?

**Comment by nitriques** [comment] 2015-02-20 18:53
> What about you?

Nope. And I am afraid to break something. I do hope @brendo feels like playing with :fire:

**Comment by brendo** [comment] 2015-02-22 07:29
A nice example of where loose comparison can have adverse effects. Fixed!

**Comment by michael-e** [comment] 2015-02-22 11:15
Confirmed, thanks!

**Closed** 2015-02-22 11:16 UTC

**Comment by nitriques** [comment] 2015-02-24 17:11
Nice one Brendan! I knew you would like to play with :fire:
