### ISSUE TITLE
Display Publish Panel Pre-populate Bug

### ISSUE THREAD

**Issue by jonmifsud** [symphonycms/symphony-2#2331] opened 2015-01-22 08:20 UTC
I'm not entirely sure if this is exclusively a "Core" issue. It's most certainly linked to the way Filters in the backend work. The screenshot below is the error I get when trying to create a new item from a Filtered view of an Association Field.

![screen shot 2015-01-22 at 09 10 05](https://cloud.githubusercontent.com/assets/859775/5852427/d39c23c8-a216-11e4-8d6e-7e62200f1c01.png)

As you might assume, the Association Field accepts/allows me to search using a text string which matches the "Associated Value" yet once using pre-populate it's expecting to have an entry id. Initially I thought that this was an issue with the Association Field which can be fixed by checking if the values are strings rather than integers and converting them. However (the documentation)[http://www.getsymphony.com/learn/api/2.5.2/toolkit/field/#displayPublishPanel] for `displayPublishPanel` reads the following:

> $data array(optional) any existing data that has been supplied for this field instance. this is encoded as an array of columns, each column maps to an array of row indexes to the contents of that column. this defaults to null.

So as a developer I should only cater for the fields which I support - thus a relation id should be an integer correct? As the dump within the screenshot shows this is passed "News". I'm not sure what would be the correct way to fix this, but at the very least we need to update the documentation to state that any supported filtering value can be passed.

**Comment by brendo** [comment] 2015-01-22 09:17
The Association Field deals with ID's mostly, so pre-population has to follow the same rules. The data that `displayPublishPanel` expects is `relation_id`'s. 

Are you able to generate a pre-populate link using an entry ID instead?

**Comment by jonmifsud** [comment] 2015-01-22 09:36
I can generate a pre-populate link using ID's *id* I search using ID's which the common user won't do. It also works fine If I use the association interface link (on the right of an article) to create a new entry.

The below is not really intuitive for the user, it's something specifically linked to filtering I believe. Is there a way we can get the field to give back the pre-populate value having used a filter? If not at the moment is it worth looking into or is there another way to go around it?

![screen shot 2015-01-22 at 10 33 17](https://cloud.githubusercontent.com/assets/859775/5853277/6a7c6504-a222-11e4-919a-439388b648f0.png)

**Comment by brendo** [comment] 2015-01-22 10:14
@nilshoerrmann implemented a solution to this for the Publish Filtering interface, I believe it involves `fetchSuggestionTypes`. It's documented [here](https://github.com/symphonycms/symphony-2/wiki/Migration-Guide-to-2.6-for-Developers#publish-filtering). See how that goes, I'll need to do it for the SBL as well by the looks of things :)

**Comment by brendo** [comment] 2015-01-22 10:34
This is what [I had to do](https://github.com/symphonycms/selectbox_link_field/commit/780d775d14e22ec8c5db1e1c9f76bd32a9567441) to make SBL work with Publish Filtering :)

**Comment by jonmifsud** [comment] 2015-01-22 10:59
Thanks I'll give it a shot and let you know, would probably be the exact same thing.

**Comment by jonmifsud** [comment] 2015-01-22 13:47
@brendo that seems to solve another part of the problem (suggestions) - When filtering I now get suggestions however when choosing a filter it still uses the String value. Hence when trying to pre-populate it still uses the string value throwing the error.

I think the problem is related to somewhere in the [content.publish.php](https://github.com/symphonycms/symphony-2/blob/integration/symphony/content/content.publish.php#L427) which sets the pre-populate query string to exactly the same thing as the filter. In case of an `association` this should somehow insert the `related_entry_id` rather than the `$encoded_value`

**Comment by brendo** [comment] 2015-01-23 02:48
Go back one step. What is generating your prepopulate link?

**Comment by jonmifsud** [comment] 2015-01-23 06:49
The `Create New` button when viewing a list filtered using the Associations Field. The screenshot below shows the page exactly before I hit the pre-populate link.

I've given this some thought I think the filtering is correct, when searching I get the pre-populated search field, and I can pick "Home" from the list, which sets the filter text to home. However the pre-populate link should use the `entry_id` in the case of associations instead of the filter text.

I don't think it's something to do with the suggestion value, for the simple reason that if I insert the entry id `1` the filter says I'm filtering using section = 1. Correct but not very user friendly considering the filter suggestions are in text not integers.

![screen shot 2015-01-23 at 07 41 45](https://cloud.githubusercontent.com/assets/859775/5870748/7beee922-a2d3-11e4-9ad0-ddb394e7f349.png)

**Comment by brendo** [comment] 2015-01-31 10:13
This is going to be a challenge to fix. Before Publish Filtering, all associations used ID's when using the `?filter` syntax. Now this is no longer the case. Publish Filtering uses the value instead of the ID, which is right because that's what an Author would expect to see.

The problem is that `?filter` and `?prepopulate` are intrinsically linked. So now `?prepopulate` will also have the human readable value instead of the ID.

So there's two options I can see:

- Somehow make prepopulate still pass through an ID
- Somehow update the fields so they can handle strings or ID's

Both require field changes, so I'm not fond of either :(

**Comment by jonmifsud** [comment] 2015-01-31 10:20
> Somehow make prepopulate still pass through an ID

Can't we make this something like an 'entry search' pulling up the ID's without touching fields? If you had to run a query using `buildDSRetrievalSQL` which I believe is the same function that does the filtering. Then you would select only the entry ID's and pass those to the pre-populate field string. Does it make sense?

**Comment by brendo** [comment] 2015-01-31 11:07
I'm not sure that'd work as expected. `buildDSRetrievalSQL` generates the joins and where clauses for a given value. In this case, if we gave it the value `Dog`, the field would return all the entries that match `Dog`. The entry ID's of these entries are not what we need, we want the original ID of `Dog`.

Now the SBL does have a function, `fetchIDfromValue`, which will do exactly what we want (in fact it's what `buildDSRetrievalSQL` calls internally), but I'm not sure how many other associated fields also implement this function. We could make it a "pseudo" recommendation though...

**Comment by jonmifsud** [comment] 2015-02-20 12:11
@brendo just tried out the latest integration, and your commits work on the Association Field too, so looks good.

**Comment by brendo** [comment] 2015-04-22 03:24
Just encountered a similar issue with 59fec35. The Taglist/Select Box fields work with Associations using values, not ID's. The prepopulate and filtering tries to use the Entry ID to help filter/prepopulate entries/fields and as such, things don't quite work as expected.

I'm afraid Associations is hardcoded to assume that linking will always be done with an ID. While we agree that this is recommended and is the more resilient way to do it, we have two core fields that don't follow this recommendation, doh.

**Comment by nitriques** [comment] 2017-06-01 21:56
This seems to be the same bug as in # 2550 ?

**Comment by nitriques** [comment] 2017-06-07 02:18
Fixed in 55a0882b !

**Closed** 2017-07-11 18:48 UTC
Labels: 2 - Nominal, Filtering UI, Fix found, Fixed in 2.7.x, PR Submitted
