### ISSUE TITLE
2.6.3 XSRF filter does not generate any token in incognito window

### ISSUE THREAD

**Issue by cmnstmntmn** [symphonycms/symphony-2#2524] opened 2015-12-04 13:54 UTC
it works, if i'm logged in, and it breaks right after i log out.

**Comment by michael-e** [comment] 2015-12-04 18:49
This is a duplicate of #2173.

**Comment by nitriques** [comment] 2016-06-15 14:46
Hum I do not think it's duplicate. @cmnstmntmn are you saying that the XSRF token is not generated in the backend (admin) ?

**Comment by cmnstmntmn** [comment] 2016-06-15 15:34
@nitriques nope, on the frontend, only in incognito window, i dont't get any token

<img width="1440" alt="screen shot 2016-06-15 at 18 33 00" src="https://cloud.githubusercontent.com/assets/2312755/16086297/b740fa20-3327-11e6-9942-a5e778594030.png">
<img width="873" alt="screen shot 2016-06-15 at 18 33 21" src="https://cloud.githubusercontent.com/assets/2312755/16086310/c25cc5ce-3327-11e6-9f05-de1b03d8137b.png">

**Comment by nitriques** [comment] 2016-06-15 21:58
Hum this is weird. I mean, it's normal that the token may not be there all the time... But should the variable should always be there.

Also, it's better to use the complete xpath query, i.e. `/data/params/node` rather than their variable `$node` counter-parts, since it won't crash the XSLT parser.

I will investigate more.

**Comment by nitriques** [comment] 2016-06-15 22:07
@cmnstmntmn Can you confirm that you can reproduce this ?

1. Open private nav, go to home page. crash
2. Type in the symphony's admin url (`/symphony/`). You see the login page.
3. Type in the home page address: not crash since the session has been started.

@michael-e Since we still support the node to variable translation, I think we should always set it (with an empty value). Yea or Nay ?

**Comment by cmnstmntmn** [comment] 2016-06-16 13:35
@nitriques yes, i confirm that!

it't works after i hit `/symphony` and i return

**Comment by nitriques** [comment] 2016-06-17 02:40
@cmnstmntmn Thanks.

**Comment by nitriques** [comment] 2016-08-15 00:54
After review, yeah, it's  "... a duplicate of #2173."

**Closed by nitriques** 2016-08-15 00:54 UTC
Labels: 1 - Minor
