### ISSUE TITLE
Install script doesn't work with database on localhost

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/symphony-2#2415] opened 2015-05-01 10:05 UTC
Not sure if my local environment is to blame here, maybe others have the same issue.

The install script on `integration` doesn't seem to recognize my database on `localhost` (which is the predefined value), but works fine for `127.0.0.1`.

Works fine with `localhost` on `2.6.x`, though.

**Comment by brendo** [comment] 2015-05-03 10:46
So what exact error do you receive? Is it `Symphony was unable to establish a valid database connection. You may need to modify host or port settings.`?

While I'm not testing the install at the moment, subbing `127.0.0.1` with `localhost` in an existing `integration` install doesn't throw any errors on my machine (PHP 5.5.23 with mysqlnd 5.0.11)

Can you confirm your PHP version, and if you have the MySQL Native Driver installed (it'll appear in the `phpinfo()`)?

**Comment by jensscherbl** [comment] 2015-05-03 11:22
> Can you confirm your PHP version

- 5.5.22
- 5.6.6

> and if you have the MySQL Native Driver installed

Installed (5.0.11).

> So what exact error do you receive? Is it `Symphony was unable to establish a valid database connection. You may need to modify host or port settings.`?

Exactly.

> subbing 127.0.0.1 with localhost in an existing integration install doesn't throw any errors on my machine

To clarify, I get the error when using `localhost`. I don't get an error and everything works as expected when using `127.0.0.1`.

**Comment by munki-boy** [comment] 2015-05-03 12:41
Installing integration works ok for me on WAMP win 8 x64 if I put localhost.  My PHP is 5.5.12 and SQL is 5.6.17. Once installed it says Symphony 3.0.0-alpha.1 in the backend.  

I have an out-of-the-box WAMP setup here having cleaned the computer a week or so ago and apart from enabling the couple of PHP extensions we need for Symphony everything else should be defaults.

**Comment by jensscherbl** [comment] 2015-05-03 12:46
> I have an out-of-the-box WAMP setup here having cleaned the computer a week or so ago and apart from enabling the couple of PHP extensions we need for Symphony everything else should be defaults.

Im using a default [MAMP][1] setup on Yosemite.

[1]: https://www.mamp.info/en/

**Comment by munki-boy** [comment] 2015-05-03 12:49
Either OS or PHP/SQL versions then? MAMP must have slightly newer versions.

**Comment by munki-boy** [comment] 2015-05-03 13:07
Hmm, forgot, I have manually added PHP etc. to the winderz PATH variable so the OS can find them.  Not usually needed for Sym install but I use it for other stuff.  You'd already have that functionality so probably not relevant but just to be clear about my setup.

**Comment by brendo** [comment] 2015-05-03 13:22
> It does for me. Didn't have that problem with previous integration "builds", though. And it also seems to work fine with 2.6.x.

2.6.x uses `mysql_*` commands to interact with the database whereas `integration` uses PDO. This is the only difference.

**Comment by munki-boy** [comment] 2015-05-03 13:26
Oh, I'm using PDO :) 

Looks like php_pdo_mysql came pre-enabled with this WAMP ver.

**Comment by brendo** [comment] 2015-05-03 13:37
There's a note on the [PHP manual](http://php.net/manual/en/ref.pdo-mysql.connection.php) which might hint that it's related to the PHP config? I'm not familiar with MAMP so can't comment on if this is true or not.

> Note: Unix only:
When the host name is set to "localhost", then the connection to the server is made thru a domain socket. If PDO_MYSQL is compiled against libmysqlclient then the location of the socket file is at libmysqlclient's compiled in location. If PDO_MYSQL is compiled against mysqlnd a default socket can be set thru the pdo_mysql.default_socket setting.

**Comment by jensscherbl** [comment] 2015-05-04 15:36
My `pdo_mysql.default_socket` has a different value (*/tmp/mysql.sock*) than `mysqli.default_socket` (*/Applications/MAMP/tmp/mysql/mysql.sock*). So this is not configured correctly and the issue is indeed expected behavior in this case?

**Comment by nitriques** [comment] 2015-05-04 15:42
> expected behavior in this case?

I think so yes. I would love to be able to do better, but as you can see in #2352, it's only a matter of php.ini setting...

**Comment by brendo** [comment] 2015-05-04 15:59
I wonder, and this could be bad in some cases, if we would be better off trying `127.0.0.1` when `localhost` is used before failing?

So it'd be:

- try `localhost`
- catch failure, try `127.0.0.1`
- catch failure and report

Ideally we should support a `unix_socket` property in the config as well to handle it.

**Comment by nitriques** [comment] 2015-05-04 16:01
@brendo I would vote for it yes, but I would like to be able to disable it.

**Comment by brendo** [comment] 2015-05-04 16:12
How? This is for installation, so it's a little soon to be using configuration parameters. Is there ever a situation where we wouldn't want it to try `127.0.0.1`?

**Comment by nitriques** [comment] 2015-05-04 16:37
>  Is there ever a situation where we wouldn't want it to try 127.0.0.1?

Yup on production servers. Installation (in my case) is never made on those servers, so I would not mind that installation would try it.

But if this feels like I am the only one with those requirements, I could live without it ;)

**Comment by michael-e** [comment] 2015-05-04 17:08
Yep, don't overcomplicate things. Since the -NIX socket connection will always be faster than a TCP/IP connection, we shouldn't build an installer automatism which can result in sub-otimal configuration (on production servers). Better modify the error message to say: "If you can't fix the socket, you may try 127.0.0.1 for development. We don't recommend this on production servers. however."

**Comment by nitriques** [comment] 2015-05-04 19:20
@michael-e I agree.

**Comment by jensscherbl** [comment] 2015-05-04 21:34
Why not simply replace localhost with 127.0.0.1 as suggested default value?

**Comment by jensscherbl** [comment] 2015-05-04 21:37
Sorry, was too quick to reply, didn't read Michael's argument first.

**Comment by nitriques** [comment] 2015-05-04 21:37
> Why not simply replace localhost with 127.0.0.1 as suggested default value?

I would not mind that at all. Even less error prone as one can redirect its localhost to anywhere else.

**Comment by nitriques** [comment] 2015-05-04 21:38
A me neither. Yeah unix socket is way faster...

**Comment by nitriques** [comment] 2015-11-29 23:21
@michael-e Would you mind sending a PR for the 'If you can't fix the socket, you may try 127.0.0.1 for development. We don't recommend this on production servers, however.' message please ?

**Comment by michael-e** [comment] 2015-11-29 23:43
I will take a look.

**Comment by nitriques** [comment] 2015-11-29 23:44
Thanks a lot.

**Comment by michael-e** [comment] 2015-11-30 18:14
I tested the installation process in order to get a feeling for the possible mistakes and corresponding error messages. First thing I noticed is: Symphony 2.6.4 displays erroneous error messages when the socket doesn't work (I used `localho` instead of `localhost`), but the integration branch gets it right. The difference might be caused by MySQL not sending the expected error codes, of course.

However, I have the feeling that we should have something like a "final, long term support (LTS) version" of Symphony 2—so should the 2.6 installer be fixed? (I won't find the time to do this, but I could help with testing, hopefully.)

**Comment by michael-e** [comment] 2015-11-30 18:30
To be more precise, here are some details: 

I used `localho` as the host.

* Symphony 2.6.4 said: `Symphony requires MySQL 5.5 or greater to work, however version was detected. This requirement must be met before installation can proceed.` (Note that we have two problems here: Wrong error message plus missing version info.)
* Symphony 3.0.0-alpha.1 (integration branch) said: `Symphony was unable to establish a valid database connection. You may need to modify host or port settings.` – correct.

**Comment by nitriques** [comment] 2015-11-30 22:49
@michael-e was it working in 2.6.3 ?

**Comment by michael-e** [comment] 2015-12-01 10:25
No, it doesn't work on 2.6.3 either. (No, I don't understand why — the logic is pretty much the same.)

**Comment by michael-e** [comment] 2015-12-01 12:43
It's hard to get the message right. Here's my suggestion, any feedback is welcome:

> Symphony was unable to establish a valid database connection. You may need to modify host or port settings. If "localhost" does not work, the socket may not be configured correctly. You might instead use a TCP/IP connection for development by setting the host to "127.0.0.1". However, we do not recommend this on production servers.

**Comment by nitriques** [comment] 2015-12-01 14:57
@michael-e We are talking about that string right ? https://github.com/symphonycms/symphony-2/blob/master/install/lib/class.installer.php#L278

**Comment by nitriques** [comment] 2015-12-01 15:00
Can you also check in the install log if ALL errors are logged ? Maybe the wrong error message is only a render problem...

**Comment by michael-e** [comment] 2015-12-01 15:06
> We are talking about that string right ? https://github.com/symphonycms/symphony-2/blob/master/install/lib/class.installer.php#L278

Correct.

> Can you also check in the install log if ALL errors are logged ? Maybe the wrong error message is only a render problem...

You mean the issue with Symphony 2.6? Indeed, with Sym 2.6 I have:

    12/01/2015 11:24 am > Fatal Error: Configuration - MySQL Version is not correct.  detected.

With the integration branch, I have:

    12/01/2015 1:42 pm > Fatal Error: Configuration - Could not establish database connection.

Could it be that MySQL doesn't output the correct error number without PDO (i.e. with Sym 2.6)?

**Comment by nitriques** [comment] 2015-12-01 15:15
Maybe... You do not have the other message logged just before ??? I mean, the 'Could not establish database connection.' should still be there in the log before the 'MySQL Version is not correct'...

And on a related note, I would try to stop the installer from getting the version if the connection did not succeed.. that's why the version is missing.

**Comment by michael-e** [comment] 2015-12-01 15:49
No, the other (correct) message has not been logged!

Can you try and test this yourself, maybe?

**Comment by nitriques** [comment] 2015-12-01 16:31
Will do, just can't right now... Thanks for your info as this will help me a lot if I have the same or different things

**Comment by nitriques** [comment] 2018-05-02 18:47
@michael-e I finally made some tests, but I cannot test every possible configuration.

I've tested Windows and Linux. Both have TCP and UNIX sock. I'll be sending a commit that should add documentation in the installer about that.

I do not think that we need to change anything, as PDO will try socket first and tcp second for localhost

> Note: Unix only:
> When the host name is set to "localhost", then the connection to the server is made thru a domain socket. If PDO_MYSQL is compiled against libmysqlclient then the location of the socket file is at libmysqlclient's compiled in location. If PDO_MYSQL is compiled against mysqlnd a default socket can be set thru the pdo_mysql.default_socket setting.

From http://php.net/manual/en/ref.pdo-mysql.connection.php

I do not think we should do anything when the user enters 127.0.0.1.

**Comment by nitriques** [comment] 2018-05-02 19:37
Indeed.

**Comment by michael-e** [comment] 2018-05-02 19:37
I suggest to close it.

**Comment by nitriques** [comment] 2018-05-02 19:38
Will be done automatically when 3.0.x will get merged into master ;)

**Closed** 2020-03-27 17:07 UTC
Labels: 1 - Minor, Fixed in 3.0.x, Needs Testing
