### ISSUE TITLE
Data source sorting of XML parameters is reversed

### ISSUE THREAD

**Issue by cylkee** [symphonycms/symphony-2#2625] opened 2016-10-13 21:59 UTC
In the Data Sources UI if I choose, say, `asc` the entries are of course sorted on the chosen field in that direction, but if I select the same sorting field to be output as a parameter and compare in XML, the sorting of the parameters is in the opposite direction. I changed some data to be sure. Vice versa for `desc`, and every refresh of `random` output is reflected with the opposite order in parameters.

**Comment by nitriques** [comment] 2017-04-28 00:58
I was not able to reproduce. Which field type is used for the sort in your example ? I tested the core input field, with the input as sorted (asc, desc, random), I've tested with and without pagination, I've tested with the input in the ds output and without. The right order remains. Can you help me reproduce it ?

**Comment by nitriques** [comment] 2017-06-01 20:37
Closed as we do not have any feedback. Please comment and we will reopen.

**Closed by nitriques** 2017-06-01 20:37 UTC
Labels: Not reproductible
