### ISSUE TITLE
Entry filter not working with titles containing Ampersands

### ISSUE THREAD

**Issue by animaux** [symphonycms/symphony-2#2446] opened 2015-05-20 07:57 UTC
`Symphony 2.6.1`

A similiar problem to this [JS-related problem](https://github.com/symphonycms/symphony-2/issues/2423):

When I try to filter a list of entries in in index view by a regular `input field` with a value containing an ampersand, the value reverts to only the word *before* the ampersand. Here are my steps:

1. create a new filter in index view, and filter by `input field` title
2. filter by value `is` and select a value from the pop-up of existing values f. e. »Bilden & Betten«
3. the filter reverts to »Bilden« and the result thus is no entry

Probably the ampersand needs to be escaped/encoded at some point and isn’t. Typing »Bilden & Betten« by hand instead of clicking the existing value yields the same result.

**Comment by michael-e** [comment] 2015-05-20 08:15
Reminds me of #2349. (But in that case escaping with a backslash helped. I don't know what's the solution for ampersands.)

**Comment by michael-e** [comment] 2015-05-20 08:17
Ah, got it: Replacing the ampersand by `%26` in the URL works. So it can probably be solved similar to #2349.

**Comment by animaux** [comment] 2015-05-20 08:20
Brilliant, sounds good! Thanks Michael.

**Comment by michael-e** [comment] 2015-05-20 08:22
Something like adding `value.replace('&', '%26');` after [this line](https://github.com/michael-e/symphony-2/blob/c9e663a8e4ec0fa171fd1b3f452e7164dfb5bdd0/symphony/assets/js/src/symphony.suggestions.js#L328). Could you test that, @animaux ?

**Comment by michael-e** [comment] 2015-05-20 08:23
Ah, sorry, again we'd only replace the first occurence with that…

**Comment by michael-e** [comment] 2015-05-20 08:31
See https://github.com/symphonycms/symphony-2/pull/2420. We must either split the string or use regex. @nitriques suggested regex last time, but we kept the split in the end. Time to give it another thought. We should make it consistent.

Solution 1:

```js
input.val(value.split(',').join('\\,'));
input.val(value.split('&').join('%26'));
```

Solution 2:
```js
input.val(value.replace(/,/g, '\\,'));
input.val(value.replace(/&/g, '%26'));
```

@nitriques, @brendo?

**Comment by brendo** [comment] 2015-05-20 10:01
Nah, this is getting a little hacky. We should fully encode the values using [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) which will handle all special characters.

**Comment by michael-e** [comment] 2015-05-20 10:20
Unfortunately, that doesnt' work, because it will encode `,` as `%2C`. For some reason we need to escape this as `\ ,`.

The output of

```js
encodeURIComponent('test1, test2 & test3');
```

is `test1%2C%20test2%20%26%20test3`, but we need `test1\,%20test2%20%26%20test3` for the filter to work correctly.

**Comment by brendo** [comment] 2015-05-20 13:08
What a bloody mess. You are correct, we need `\,` because the
`Datasource::determineFilterType` looks for the specific pattern of commas
escaped by backslashes.

Perhaps the Q&D method is the best way after all.

**Comment by michael-e** [comment] 2015-05-20 13:13
Which route? Split or regex replace? (I am by no means an expert in JS.)

**Comment by brendo** [comment] 2015-05-20 13:22
Either or, something like the following should do the trick:

```js
value = value.replace(/,/g, '\\,').replace(/&/g, '%26');
input.val(value);
```

**Comment by michael-e** [comment] 2015-05-20 13:43
Looks good to me, but needs testing nevertheless. Shall we pass the testing job to @animaux? :-)

It's [this line](https://github.com/michael-e/symphony-2/blob/c9e663a8e4ec0fa171fd1b3f452e7164dfb5bdd0/symphony/assets/js/src/symphony.suggestions.js#L328):

```js
input.val(value.split(',').join('\\,'));
```

which would be replaced by these two lines:

```js
value = value.replace(/,/g, '\\,').replace(/&/g, '%26');
input.val(value);
```

**Comment by animaux** [comment] 2015-05-20 13:55
Ok, did that. Do I have to recompile `symphony.min.js` or is this done on-the-fly? In case not, how do I do this?

**Comment by michael-e** [comment] 2015-05-20 13:56
Ah, I just noticed that it's a bit hard to test, because Symphony sends the minified JS file…

I have no idea how to recompile the minified file ("correctly"). Last time I hacked into the minified file in order to test the stuff.

**Comment by brendo** [comment] 2015-05-20 14:01
Actually that's a good point, @nilshoerrmann @nitriques are we able to write up a few lines about how to install/recompile the minified assets and add them to the Contributing guide?

@animaux It's done using grunt, but I'm not super familiar with the full steps to get grunt installed. I think it's just a `npm install` from the root directory (to get the dependencies) and then run `grunt` to actually perform the tasks.

**Comment by michael-e** [comment] 2015-05-20 14:06
Once again I hacked the minified file. I replaced `.split(",").join("\\,")` with `.replace(/,/g, '\\,').replace(/&/g, '%26')`, and it worked fine. So we should be fine with @brendo's code!

**Comment by jonmifsud** [comment] 2015-05-20 14:10
@brendo those should be the steps. I've set it up to do some modifications before.

**Comment by animaux** [comment] 2015-05-20 14:13
@michael-e I’m not able to find `.split(",").join("\\,")` in my `symphony.min.js`. Symphony 2.6.2. Are you in the integration branch?

**Comment by michael-e** [comment] 2015-05-20 14:14
No, I am on Symphony 2.6.2. I can find the string. Which editor do you have?

**Comment by animaux** [comment] 2015-05-20 14:17
BBEdit 11.1

**Comment by animaux** [comment] 2015-05-20 14:23
m( d’oh: hadn’t reloaded the file in the editor after the 2.6.2 update … found it.

**Comment by nilshoerrmann** [comment] 2015-05-20 14:25
> Actually that's a good point, @nilshoerrmann @nitriques are we able to write up a few lines about how to install/recompile the minified assets and add them to the Contributing guide?

@nitriques might be better at this job.

**Comment by animaux** [comment] 2015-05-20 14:25
Work’s fine for me! Tested with:

+ Ampersand
+ Umlaut (ä, ö, ü)
+ Regular Characters + Spaces

Cheers!

**Comment by nitriques** [comment] 2015-05-22 17:11
@brendo @nilshoerrmann 
Sorry it took so long, but, here it is: https://github.com/symphonycms/symphony-2/wiki/Building-the-client-assets-files

I've also added a link to it on the home page.

Is it missing something ?

**Comment by brendo** [comment] 2015-05-23 07:27
Pushed the fix for real :)

**Closed by brendo** 2015-05-23 07:27 UTC

**Comment by michael-e** [comment] 2015-05-23 09:30
The page is completely gone: https://github.com/symphonycms/symphony-2/wiki/Building-the-client-assets-files

I know it was there, I saw it. How can that be?

**Comment by michael-e** [comment] 2015-05-23 09:31
Re: The fix: Confirmed that it works as advertised. ( @animaux )

**Comment by brendo** [comment] 2015-05-23 10:04
Sorry, that was me, I thought Github pages did automatic redirects, https://github.com/symphonycms/symphony-2/wiki/Building-Symphony%27s-Assets

**Comment by michael-e** [comment] 2015-05-23 10:06
Ah, thanks!

**Comment by nitriques** [comment] 2015-05-25 15:24
Oh sorry for the typo!

And is the doc ok ?

**Comment by michael-e** [comment] 2015-05-26 08:04
Yeah, sure! I just had to do install grunt-cli as well (`npm install -g grunt-cli`) in order to make it work for me.

**Comment by nitriques** [comment] 2015-05-26 14:24
Totally true. It's not grunt that you need to install globally, it's the cli.

I will update the doc accordingly. Thanks

**Comment by animaux** [comment] 2015-05-27 14:04
@michael-e Prima, thanks! :)

**Comment by michael-e** [comment] 2015-05-27 14:16
You're welcome.
