### ISSUE TITLE
Multi-select dropdown scrollbars don't work in Safari

### ISSUE THREAD

**Issue by nathanhornby** [symphonycms/symphony-2#2347] opened 2015-02-09 14:58 UTC
~~I have a feeling that this is a Safari (v. 8, build 10600.1.25) bug (as it seems fine in Chrome), but thought I'd report it for reportings sake~~

The scrollbars on the multi-select dropdown lists (for example on the Datasource editor page, example attached) can't be manually scrolled using the scrollbar (I don't use a scrollwheel type device, so grab handles manually).

Anyone able to confirm this?

![screen shot 2015-02-09 at 14 54 59](https://cloud.githubusercontent.com/assets/1975168/6108546/ef9eb50a-b06b-11e4-83bb-1bf10580316d.png)

**Comment by nathanhornby** [comment] 2015-02-09 15:04
Just did a quick test - actually this *does* seem to be something specific to Symphony. I just set up a basic jsfiddle and I can manually scrob through the list using the handle. So something is preventing it from working in the Symphony backend, but only in Safari…

**Comment by michael-e** [comment] 2015-02-09 15:07
In Safari 6 the scrollbars are even invisible until scrolling starts. Once they are shown, they can not be dragged.

**Comment by nathanhornby** [comment] 2015-02-09 15:24
@michael-e That's actually due to OS level settings - I have forced scrollbar display, due to my use. (so probably unrelated)

![screen shot 2015-02-09 at 15 23 57](https://cloud.githubusercontent.com/assets/1975168/6108998/ae96102c-b06f-11e4-9eed-e9c4d2359b83.png)

**Comment by nitriques** [comment] 2015-02-09 15:38
@nathanhornby Can you check if removing overflow: hidden fixes the problem ?

Also, this changing your OS setting fixes the problem ?

**Comment by nathanhornby** [comment] 2015-02-09 15:44
@nitriques What's the overflow: hidden applied to? I can't track it down!

> Also, this changing your OS setting fixes the problem ?

No this should be unrelated. If I had either of the other options selected I wouldn't see the scrollbar, and wouldn't be able to make it appear as I don't have a scroll device. (hopefully that makes sense).

**Comment by nitriques** [comment] 2015-02-09 16:27
>  What's the overflow: hidden applied to? 

The selectbox or any of its parent...

> Would be good to see if someone can at least scroll in that little window,

I can on Windows + Chrome...

**Comment by nathanhornby** [comment] 2015-02-09 16:56
@nitriques I can't see any forced overflow properties on the elements I'm afraid - if there definitely is one feel free to point me at it!

I've just checked on my Macbook, and you can scroll (with the trackpad) within the box, but as soon as you turn on scrollbars (OS level setting) and manually try to move the handle, it doesn't work. Again, this is only in Safari, Chrome handles the manual scrollbar handles just fine in Symphony.

So it must be something oddly specific in the way those select's are presented. Overflow would be a good place to start (if I'm missing one), if not I'm not sure what I'd check next…

**Comment by nitriques** [comment] 2015-02-09 17:37
Really weird. You are running the latest integration ?

**Comment by nathanhornby** [comment] 2015-02-09 17:41
Haven't tested on integration, but it's the case on 2.5.2.

**Comment by nitriques** [comment] 2015-02-09 20:40
Ok

> But importantly anyone on Yosemite and Safari should be able to reproduce the issue.

This means that you tested multiple computers with Yosemite ?

**Comment by nathanhornby** [comment] 2015-02-09 21:03
Yup, 2 machines, different symphony sites, different input devices.

**Comment by nitriques** [comment] 2015-02-09 21:03
ok thanks nathan.

**Comment by brendo** [comment] 2015-02-10 09:48
Bah, don't tell me #2125 has come back again.

**Comment by nathanhornby** [comment] 2015-02-10 09:52
@brendo I don't believe so, unless I'm missing something, or you referenced the wrong issue? (colour me confused)

**Comment by nitriques** [comment] 2015-02-10 15:17
Could it be related to #2231 ?

I would really like it if you could test it with the latest integration code. I can't reproduce it..

**Comment by michael-e** [comment] 2015-02-10 15:56
For me it's the same with the latest integration code: It's impossible to drag the scrollbar.

**Comment by nitriques** [comment] 2015-02-10 16:05
But the mousewheel (touchpad) still works right ?

**Comment by michael-e** [comment] 2015-02-10 16:10
Yep, scrolling on the touchpad works fine.

**Comment by nitriques** [comment] 2015-02-10 16:11
http://stackoverflow.com/questions/27109190/safari-8-multiple-select-scrolling-issue ?

**Comment by michael-e** [comment] 2015-02-10 16:40
I can confirm that this is the issue. The second example link in the thread shows the same behaviour (tested in Safari 6.2.3).

**Comment by nitriques** [comment] 2015-02-10 16:59
Isn't Safari 6 kind of old ? Nathan's issue was with Safari 8... So the bug spans 3 version of Safari ?

**Comment by nathanhornby** [comment] 2015-02-10 17:00
Could be related!

I tested a multi select in jsfiddle and it worked fine, however I didn't apply any CSS styling - so if it is something to do with the width I wouldn't have seen it!

Maybe this is one we'll have to keep an eye on, and hope it's fixed in a new Safari build?

**Comment by nathanhornby** [comment] 2015-02-10 17:10
Safari 6? So is it a Yosemite issue then? Must be something wrong with the new UI.

**Comment by nitriques** [comment] 2015-02-10 17:10
Safari 6 cannot run on Yosemite...

**Comment by nathanhornby** [comment] 2015-02-10 17:12
Duh! Good point.  Clarification from Michael needed then :)

**Comment by michael-e** [comment] 2015-02-10 17:16
> Isn't Safari 6 kind of old ? 

It's the latest version on OS X 10.8.5 (which I still use). And yes, the issue is the same in this version of Safari..

**Comment by nitriques** [comment] 2015-02-10 17:33
Hum interesting.

**Comment by brendo** [comment] 2015-05-13 10:49
Are we any closer to discovering how to resolve this or reproduce it reliably?

**Comment by michael-e** [comment] 2015-05-13 10:57
It is still reproducable for me in Safari 6.2.6 (on OS X 10.8.5). Scrollbars can not be dragged.

**Comment by michael-e** [comment] 2015-05-13 11:05
I did some quick tests, deactivating CSS decalarations in the debugger. The issue seems to be caused by applying a width of `50%` on the surrounding `label` element. We might try and apply the width to a `div`, then include the label and the select in the div.

**Comment by michael-e** [comment] 2015-05-13 11:20
Nope, the idea above (applying the column class to a surrounding `div` element) doesn't seem to work either. Will need more research. (But I will be AFK for a while.)

**Comment by michael-e** [comment] 2015-05-13 11:52
To me it looks like a Safari bug. Even in this simple example, the scrollbar is not draggable in my version of Safari:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Test</title>
</head>
<body>
	<form action="">
		<label for="test1">Test 1</label>
		<select id="test1" name="test1" multiple="multiple">
			<option>something</option>
			<option>some other thing</option>
			<option>three are more than two</option>
			<option>I need 4, or even 10</option>
			<option>Shouldn't be too hard</option>
			<option>I think I have nearly 20 now, or at least 6</option>
			<option>non sense</option>
			<option>sense</option>
			<option>Bug in Safari</option>
			<option>Bug in Symphony</option>
		</select>
	</form>
</body>
</html>
```

Does anybody have example code with draggable scrollbars in Safari? @nathanhornby?

**Comment by nathanhornby** [comment] 2015-05-13 12:41
@michael-e definitely seems to be a bug in Safari to be fair, as you point out @michael-e: http://jsfiddle.net/h7w1m3g7/

Oddly if you click in the empty area in the bar (not the handle) then the handle jumps to it, but you can't grab and move the handle.

IMO issue should probably be closed.

**Comment by michael-e** [comment] 2015-05-13 12:56
> Oddly if you click in the empty area in the bar (not the handle) then the handle jumps to it, but you can't grab and move the handle.

Yep, that's odd. Same here.

> IMO issue should probably be closed.

So do I think. Closing.

**Closed by michael-e** 2015-05-13 12:56 UTC
Labels: Needs Test Case

**Comment by brendo** [comment] 2015-05-13 13:34
Ok then, perhaps it's worth following up with Safari's bug tracker (not sure what that is TBH) to see what the deal is. The JS Fiddle is excellent as it clearly highlights it's a native issue regardless of CSS/JS. Thanks for whipping that up :)

**Comment by nathanhornby** [comment] 2015-05-13 14:18
No problem!

You know, I have a feeling I might have filed the report with the Apple bug tracker already (I mistakenly thought we'd come to the conclusion that it was a Safari bug already - I wonder if a discussion continued elsewhere), although in my experience reporting bugs to Apple is like throwing them in the bin.

**Comment by michael-e** [comment] 2015-05-13 14:25
> Thanks for whipping that up

You're welcome!

**Comment by munki-boy** [comment] 2015-05-13 16:34
Don't Apple cut and paste the bug list into the feature list for the next ver. :P

**Comment by Shivamarbutus** [comment] 2019-12-04 07:38
Multiple select is working like dropdown on click the select box. This issue is generated on safari tab view.
