### ISSUE TITLE
Arrow symbols in table headers don't reflect sort order when filtering is applied

### ISSUE THREAD

**Issue by michael-e** [symphonycms/symphony-2#2707] opened 2017-06-13 17:07 UTC
On index pages, header cells of sortable fields have small arrow symbols showing the current sort order (when sorting has been applied on a column).

This does not work, however, when filtering is applied — look at the "Title" column here:

<img width="637" alt="bildschirmfoto 2017-06-13 um 19 02 01" src="https://user-images.githubusercontent.com/40072/27094653-1bacdb08-506b-11e7-9cd3-5f76fd5d0132.png">

This bug occurs in Symphony 2.6.11 and 2.7.x (as of today) alike.

**Comment by nitriques** [comment] 2017-06-13 17:52
I've reproduced the bug in 2.7.x branch.

I've just tested #2696 and it works, when the filtering yields more than one result. Only if you "unsort" (I do not know how to do it via the UI) will you lose the filter.

**Comment by nitriques** [comment] 2017-06-13 18:03
Found it !
Turns out it is only a css problem ;)

**Comment by michael-e** [comment] 2017-06-13 18:04
There is no way to unsort via the UI, AFAIK. You must append `?unsort` to the URL.

**Comment by nitriques** [comment] 2017-06-13 18:04
Should we still keep filters ?

**Comment by michael-e** [comment] 2017-06-13 18:05
Sure!

**Comment by nitriques** [comment] 2017-06-13 18:38
@michael-e I've added commit to fix this into #2696 since the fix for this commit was needed to fix this issue (I kept losing the filter and it was driving me crazy)

**Closed** 2017-07-11 18:39 UTC
Labels: 1 - Minor, Fix found, Fixed in 2.7.x, PR Submitted
