### ISSUE TITLE
Core checkbox UI filtering on 'No' fails if field added retrospectively

### ISSUE THREAD

**Issue by cylkee** [symphonycms/symphony-2#2692] opened 2017-06-01 10:14 UTC
Steps to reproduce in v2.6.11 and workaround:

1. create a section with a text field or two
2. create several entries in this section
3. edit the section and add a checkbox field
4. add another entry (leave checkbox unticked)
5. filter entries in the UI on that checkbox and select No from the drop-down suggestion list
6. the filter only finds those entries created _after_ the checkbox was added to the section
7. remove the filter and observe all entries say No in checkbox column
8. Select all entries and use the With selected... drop-down to apply No to the checkbox field you added
9. repeat step 5 and now all other entries appear in the filter as expected

**Comment by nitriques** [comment] 2017-06-01 18:36
This as already been discussed and the resolution was that it is the intended behaviour: By default adding a field does not create any records for existing entries.

It is understandable that it can be confusing to have a third, NULL state to the checkbox. But it would be a breaking thing to do.

See https://github.com/symphonycms/symphony-2/issues/1523 for the full discussion.

I'll leave the issue open, since it could be a go idea to force that behavior, with a field setting. cc @brendo

**Comment by brendo** [comment] 2017-06-01 22:53
Maybe a different approach is to expose those entries to the filter using 'Not set'/'No value' or equivalent wording.

**Comment by nitriques** [comment] 2017-06-02 00:53
Would "is empty"/"is not empty" work ? We already have it for the input field..

**Comment by cylkee** [comment] 2017-06-02 10:23
I think to display 'No' in the columns and offer 'No' in the filter drop-down suggestion list is misleading in the UI, in this case.  Is it possible to either set all entries to No when a checkbox is added restrospectively or display nothing in the column?

**Comment by michael-e** [comment] 2017-06-02 10:34
+1 for always displaying the actual value (which is an empty string in this case).

**Comment by brendo** [comment] 2017-06-02 14:08
Agree @cylkee, we have the faded 'None', should this be used instead?

**Comment by nitriques** [comment] 2017-06-02 20:10
@brendo @michael-e `prepareTextValue` implementation is based on the `ExportableField` interface. Should we change the behaviour of the export as well ? That would be a breaking change...

And if we change the UI, we might wanna offer the filtering also, no ?

**Comment by michael-e** [comment] 2017-06-02 20:44
It always bothered me that even if I add a Checkbox that is "checked by default", I see a value of "No" on the section's index page. So @brendo's suggestion (the faded "None") is much more logical.

Regarding the export, do we really export a value of "no"? (I never tested such an export — for the reasons mentioned above I always re-save all entries using a background script after adding a new checkbox, so in my systems all checkbox values are "real" values.)

**Comment by michael-e** [comment] 2017-06-02 20:47
Trying to look at it from the other side: Are we destroying a "beloved" Symphony convention? Is this "Symphony style"? An empty value means "no", just like "no" means "no"? Only a checked checkbox is "yes"?

**Comment by michael-e** [comment] 2017-06-02 21:01
I tested that Symphony does not output any value for a checkbox field as long as older entries have not been resaved (which means that the checkbox has no value for these entries). This makes sense in "Symphony's thinking" — it always drops fields withut a value from XML output.

But then indeed it is misleading to display a value of "No". @brendo's suggestion is the right thing to do (or maybe an empty cell in the column).

I would expect Symphony to also export no value in these cases.

And yes, I would expect Symphony to let me filter by an empty checkbox value as well.

**Comment by nitriques** [comment] 2017-06-05 21:28
Agreed. This will be then postponed, because it is a breaking change.

**Comment by nitriques** [comment] 2017-06-16 01:05
@cylkee This has been partially fixed in `2.7.x` since you can know filter by 'empty' checkboxes

**Closed** 2020-03-27 17:07 UTC
Labels: 2 - Nominal, Enhancement, Feature Request, Fix found, Fixed in 3.0.x, PR Submitted
